### PR TITLE
Assignment2.a Done

### PR DESCRIPTION
**Pull request by javo-l**

### CODE REVIEW

**Comment by ocorcho** [comment]
Contributions are ok, but there is something strange in some README files that you are resubmitting.

**Comment by rgcmme** [comment]
* You are removing files from the repository.
* The hands-on materials must be inside a directory with a group number.

**Comment by rgcmme** [comment]
Check the conflicts in the pull request.

**Comment by javo-l** [comment]
I have already changed and reviewed files modified and I am not sure why some README appears to be edited since I have not wirtten anything on assignments 3 and 4, for example. I have deleted, pull and push back (after merge from the main repository). Hope it's fixed by now. If that is not the case I have no clue what to do if it already says I have not conflicts with the base branch. Thank you in advance.

**Comment by javo-l** [comment]
I have taken down this pull request in order to make a cleaner pull request with my changes (and no other changes that I have not made).

**Pull request closed without merging**
